# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           totpm
Version:        0.1.0
Release:        1%{?dist}
Summary:        A TPM-backed command line TOTP client. Like Google Authenticator in your terminal.

SourceLicense:  MIT
License:        MIT
URL:            https://github.com/koditoriet/totpm
Source0:        totpm-%{version}.tar.gz
Source1:        totpm.sysusers

BuildRequires:  swtpm
BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  systemd-rpm-macros
%{?sysusers_requires_compat}

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n totpm-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -p -D -m 0644 %{SOURCE1} %{buildroot}%{_sysusersdir}/totpm.conf
install -p -D -m 0644 totpm.conf %{buildroot}/etc/totpm.conf
mkdir -p %{buildroot}/var/lib/totpm

%pre
%sysusers_create_compat %{SOURCE1}

%if %{with check}
%check
%cargo_test
%endif

%files
%attr(0644, root, root) %{_sysusersdir}/totpm.conf
%config %attr(0644, root, root) /etc/totpm.conf
%attr(0644, root, root) %license LICENSE
%attr(0644, root, root) %license LICENSE.dependencies
%attr(4755, totpm, totpm) %{_bindir}/totpm
%dir %attr(0700, totpm, totpm) /var/lib/totpm

%changelog
%autochangelog
