[package]
name = "testutil"
version = "0.1.0"
edition = "2021"

[features]
dbus = ["dep:dbus", "dep:dbus-crossroads"]

[dependencies]
dbus = { version = "0.9.7", optional = true }
dbus-crossroads = { version = "0.5.2", optional = true }
rand = "0.8.5"
tempfile = "3.11.0"
