name: Run unit tests
on: [push]
jobs:
    unit-tests:
        name: Unit tests
        runs-on: [self-hosted, x64]
        steps:
            - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
            - name: Check out repo
              uses: actions/checkout@v4
            - run: |
                . "$HOME/.cargo/env"
                cargo test
                dbus-run-session cargo test --features=install,dbus-tests
    clippy:
        name: Clippy
        runs-on: [self-hosted, x64]
        steps:
            - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
            - name: Check out repo
              uses: actions/checkout@v4
            - run: |
                . "$HOME/.cargo/env"
                cargo clippy
                cargo clippy --features=install,dbus-tests
